items:
  - name: About
    img: https://www.evernote.com/l/AOKAp0ewB3VOo7c2MxLUiqZXM0YpTgXI6WQB/image.jpg
    url: /about
    description: 自己紹介
    tags: []
  - name: Blog
    img: https://www.evernote.com/l/AOKxw4fupE5E85xlebyVAqRCOJrs0vvlDzwB/image.jpg
    description: ブログです
    url: http://phiary.me
  - name: phina.js
    img: https://www.evernote.com/l/AOLCbNqDCH5Ph4GwxFVxphb0hZSpMbamgRcB/image.png
    description: ゲームライブラリです.
    url: http://phinajs.com
    tags: ["library"]
  - name: Runstant
    img: https://www.evernote.com/l/AOI2Sc0z9ANFH5cOd8-z-SECIcW1d6z30A4B/image.jpg
    description: Web 上でコーディングができるツールです.
    url: http://runstant.com
    tags: ["tool"]
  - name: Flick Arrow
    img: https://www.evernote.com/l/AOLvMAbjRA1AgqZIf-HjBNg5GRB0e9Tu-osB/image.jpg
    description: phina.js で作ったゲームアプリです.
    url: http://flickarrow.phinajs.com/
    tags: ["game", "app"]
  - name: 暇人の遊び
    img: https://www.evernote.com/l/AOKAp0ewB3VOo7c2MxLUiqZXM0YpTgXI6WQB/image.jpg
    description: phina.js で作ったゲームアプリです.
    url: hoge.html
    tags: ["game", "app"]
    visible: false
